/*===================================
メタデータの設定等しているファイル
googlfonntoの読み込みとか
====================================*/

// Google　フォントの設定
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { NavigationProvider } from '@/contexts/NavigationContext';
import MainLayout from '@/components/layouts/MainLayout';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}*/


export const metadata: Metadata = {
  title: '勤怠管理システム',
  description: '従業員の勤怠管理、シフト管理、休暇申請を一括管理できるシステム',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <NavigationProvider>
          <MainLayout>{children}</MainLayout>
        </NavigationProvider>
      </body>
    </html>
  );
}